IntraNet.Mod.RDV/Controllers/DespesasAnexoController.cs
using AutoMapper;
using IntraNet.Data.Context;
using IntraNet.Domain.Entities;
using IntraNet.Mod.RDV.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;


namespace IntraNet.Mod.RDV.Controllers
{
    public class DespesasAnexoController : Controller
    {
        // GET: DespesasAnexo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManegeImages(int id)
        {
            return View();
        }
        public ActionResult ListImages(int id)
        {
            ContextRDV db = new ContextRDV();
            List<DespesaAnexo> desp = db.DespesaAnexo.Where(da=>da.RelatorioId ==id).ToList();
            var DespesasAnexosDomain = Mapper.Map<List<DespesaAnexo>,List<DespesaAnexoViewModel>>(desp);
            return View(DespesasAnexosDomain);
        }
        [HttpPost]
        public JsonResult Create(DespesaAnexoViewModel despesas)
        {
            ContextRDV db = new ContextRDV();
            foreach (var ImageFile in despesas.ImageFile)
            {
                if (ImageFile.ContentLength > 0)
                {
                    DespesaAnexo desp = new DespesaAnexo();
                    string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                    string extension = Path.GetExtension(ImageFile.FileName);
                    fileName = fileName+extension;
                    desp.ImagePath = "/Relatorios/Despesas/" + fileName;                
                    desp.RelatorioId = despesas.RelatorioId;
                    fileName = HttpContext.Server.MapPath("~/Relatorios/Despesas/" + fileName);
                    ImageFile.SaveAs(fileName);
                    db.DespesaAnexo.Attach(desp);
                    db.DespesaAnexo.Add(desp);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Comprovante inserido com sucesso" }, JsonRequestBehavior.AllowGet);
                }
                
            }
            return Json(new { success = false, message = "Não foi possivel inserir o comprovante." }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Slider(int id)
        {
            ContextRDV db = new ContextRDV();
            var imagens = db.DespesaAnexo.Where(r => r.RelatorioId == id);
            ViewBag.Despesas = imagens;
            return View();
        }
    }
}

IntraNet.Mod.RDV/Views/DespesasAnexo/ListImages.cshtml
@model List<IntraNet.Mod.RDV.Models.ViewModel.DespesaAnexoViewModel>
@{
    Layout = null;
}
<div id="demo" class="carousel slide" data-ride="carousel">    
    <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
    </ul>
    <div class="carousel-inner" role="listbox">
        @{int i = 0;}
        @foreach (var item in Model)
        {
                i++;
                var active = i == 1 ? "active" : "";
                <div class="carousel-item @active">
                    <img src="@item.ImagePath" alt="" width="350">
                </div>
        }
    </div>
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>

</div>  

IntraNet.Mod.RDV/Views/DespesasAnexo/ManegeImages.cshtml
@model IntraNet.Mod.RDV.Models.ViewModel.DespesaAnexoViewModel
@{
    Layout = null;
}
<h2>Gerenciar Comprovantes.</h2>
<hr/>
    <div id="result"></div>
    @Html.Action("Slider", "DespesasAnexo", new { id = 4 })    
        <div class="form-group">
            <form method="post" id="Create" enctype="multipart/form-data">
                <div class="row">
                    @Html.Label("Comprovantes:")
                    <div class="col-lg-12">
                        @Html.TextBoxFor(model => model.ImageFile, new { type = "file", accept = ".png, .jpg, .jpeg", multiple = "multiple" })
                    </div>
                </div>
            </form>
            <hr />
        </div>
    <div>
        <div class="row col-lg-12">
            <button class="btn btn-default" onclick="DespesasAnexoCreate()">Salvar</button><button class="btn btn-default">Cancelar</button>
        </div>
    </div>

IntraNet.Mod.RDV/Views/DespesasAnexo/Slider.cshtml
@{
    Layout = null;
    var idcont = "#carousel";
    var idcarousel = "carousel";
}
<div class="carousel slide" data-ride="carousel">
    <div id="@idcarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            @{ int cont = 0;}
            @foreach (var item in ViewBag.Despesas)
            {
                cont++;
                <li data-target="@idcarousel" data-slide-to="cont" class="active"></li>
            }
        </ol>
        <div class="carousel-inner" role="listbox" id="carosel">
            @{int i = 0;}
            @foreach (var item in ViewBag.Despesas)
            {
                i++;
                var active = i == 1 ? "item active" : "item";
                var slide = "slide" + i;
                <div class="@active" id="@slide">
                    <img src="@item.ImagePath.Replace("~", "")" alt="Entrar em contato" style="height: 290px; min-width: 360px; width: auto" align="left" />
                    <div class="carousel-caption">
                      
                    </div>
                </div>

            }
        </div>
    </div>
    <a class="carousel-control left" href="@idcont" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="carousel-control right" href="@idcont" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>