IntraNet.Mod.RDV/Models/ViewModel/SetorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using IntraNet.Domain.Entities;
using System.ComponentModel.DataAnnotations.Schema;

namespace IntraNet.Mod.RDV.Models.ViewModel
{
    public class SetorViewModel
    {
        [Key]
        public int SetorId { get; set; }

        [Required(ErrorMessage = "*Insira o nome do departamento!")]
        [MinLength(2, ErrorMessage = "*Insira o nome!")]
        public string Nome { get; set; }
        public string Observacao { get; set; }
        
    }
}

IntraNet.Mod.RDV/Controllers/SetorController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using IntraNet.Data.Context;
using IntraNet.Data.Repositories;
using IntraNet.Domain.Entities;
using System;
using IntraNet.Mod.RDV.Models.ViewModel;
using AutoMapper;

namespace IntraNet.Mod.RDV.Controllers
{
    [Authorize]
    public class SetorController : Controller
    {
        private SetorRepository _rep = new SetorRepository();
        private ContextRDV db = new ContextRDV();

        // GET: Setores
        public ActionResult Index()
        {
            return View(db.Setor.ToList());
        }

        // GET: Setores/Details/5
        public ActionResult Details(int id)
        {
            Setor setor = _rep.RecuperarPorID(id);
            if (setor == null)
            {
                return HttpNotFound();
            }
            return View(setor);
        }

        // GET: Setores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Setores/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SetorId,Nome,Observacao")] SetorViewModel setor)
        {
            var msg = "";
            if (ModelState.IsValid)
            {
                var SetorDomain = Mapper.Map<SetorViewModel, Setor>(setor);
                _rep.Inserir(SetorDomain);
                msg = "Concluido, inserido com sucesso!";
                this.ViewBag.Mensagem = msg;
                return RedirectToAction("Index", "Administrador");
            }
            else
            {
                msg = "Ocorreu um erro verifique os campos do formulário";
                this.ViewBag.Mensagem = msg;
                //return Content("<script language='javascript' type='text/javascript'>alert('Não é possivel inserir o setor!')</ script>");
            }
            return RedirectToAction("Index", "Administrador");
        }

        // GET: Setores/Edit/5
        public ActionResult Edit(int id)
        {
            Setor setor = _rep.RecuperarPorID(id);
            if (setor == null)
            {
                return HttpNotFound();
            }
            return View(setor);
        }

        // POST: Setores/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SetorId,Nome,Observacao")] Setor setor)
        {
            if (ModelState.IsValid)
            {
                _rep.Alterar(setor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(setor);
        }

        // GET: Setores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Setor setor = db.Setor.Find(id);
            if (setor == null)
            {
                return HttpNotFound();
            }
            return View(setor);
        }
        public JsonResult GetSetor(string sidx, string sort, int page, int rows)
        {
            sort = (sort == null) ? "" : sort;
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;

            var EmpList = _rep.GetAll().Select(
                t => new
                {
                    t.SetorId,
                    t.Nome,
                    t.Observacao
                });
            int totalRecords = EmpList.Count();
            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
            if (sort.ToUpper() == "DESC")
            {
                EmpList = EmpList.OrderByDescending(t => t.SetorId);
                EmpList = EmpList.Skip(pageIndex * pageSize).Take(pageSize);
            }
            else
            {
                EmpList = EmpList.OrderBy(t => t.SetorId);
                EmpList = EmpList.Skip(pageIndex * pageSize).Take(pageSize);
            }
            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = EmpList
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        // POST: Setores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Setor setor = db.Setor.Find(id);
            db.Setor.Remove(setor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IntraNet.Mod.RDV/Views/Setor/Create.cshtml
@model IntraNet.Mod.RDV.Models.ViewModel.SetorViewModel

@{
    ViewBag.Title = "Create";
    Layout = null;
}

<h2><i class="glyphicon glyphicon-plus">&nbsp;</i>&nbsp;Cadastro de Novo Setor</h2>


@using (Html.BeginForm("Create", "Setor", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    <h4>Formulário para Cadastro</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, "Nome do Setor:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="row" align="right">
            <div class="col-md-12">
                <button type="submit" class="btn btn-default">Salvar&nbsp;<i class="glyphicon glyphicon-ok"></i></button>
                <button type="button" value="Salvar" id="Cancelar" class="btn btn-default" onclick="Finaliza()"> Cancelar &nbsp;<i class="glyphicon glyphicon-remove"></i></button>
            </div>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

IntraNet.Mod.RDV/Views/Setor/Delete.cshtml
@model IntraNet.Mod.RDV.Models.ViewModel.SetorViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IntraNet.Mod.RDV/Views/Setor/Edit.cshtml
@model IntraNet.Mod.RDV.Models.ViewModel.SetorViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Departamento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SetorId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}