IntraNet.Mod.RDV/Models/ViewModel/RateioItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using IntraNet.Domain.Entities;

namespace IntraNet.Mod.RDV.Models.ViewModel
{
    public class RateioItemViewModel
    {
        [Key]
        public int RateioItemId { get; set; }
        public int SolicitaCCustoId { get; set; }
        public string Item { get; set; }
        public int UnidadeClasse { get; set; }
        public int RelatorioId { get; set; }
        public int EmpCCustoId { get; set; }
        public string Prospect { get; set; }
        [Required(ErrorMessage = "Dê um valor")]
        [Range(100, int.MaxValue, ErrorMessage = "Não é possivel inserir um valor acima de 100%")]
        public int Porcentagem { get; set; }
        [ForeignKey("RelatorioId")]
        public virtual Relatorio relatorio { get; set; }
        [ForeignKey("EmpCCustoId")]
        public virtual EmpCCusto empsCCusto { get; set; }
        [ForeignKey("SolicitaCCustoId")]
        public virtual SolicitaCCusto solicitacustoid { get; set; }
        [ForeignKey("UnidadeClasse")]
        public virtual Unidade unidade { get; set; }
    }
}

IntraNet.Mod.RDV/Controllers/RateioItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IntraNet.Data.Context;
using IntraNet.Domain.Entities;

namespace IntraNet.Mod.RDV.Controllers
{
    public class RateioItemsController : Controller
    {
        private ContextRDV db = new ContextRDV();

        // GET: RateioItems
        public ActionResult Index(int id)
        {
            var rateioItems = db.RateioItems.Where(r => r.RelatorioId==id).Include(r => r.relatorio).Include(r => r.empsCCusto)
                .Include(u => u.unidade);
            return View(rateioItems.ToList());
        }

        // GET: RateioItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RateioItem rateioItem = db.RateioItems.Find(id);
            if (rateioItem == null)
            {
                return HttpNotFound();
            }
            return View(rateioItem);
        }

        // GET: RateioItems/Create
        public ActionResult Create(int id,string UserId)
        {
            var empid = db.Relatorio.Where(e => e.RelatorioId == id).Select(e => e.EmpresaId).FirstOrDefault();
            var querysolicita = from se in db.SolicitaCusto.Where(se => se.UserId == UserId && se.EmpresaId == empid)
                join cc in db.EmpresaCC on se.EmpCCustoId equals cc.EmpCCustoId
                select new
                {
                    se.SolicitaCCustoId,
                    cc.CCustoDesc
                };
            ViewBag.Item = db.SolicitaEmpresas.Where(s => s.UserId == UserId && s.EmpresaId == empid)
                .Select(s => s.Fornecedor).SingleOrDefault();
            ViewBag.SolicitaCCustoId = new SelectList(querysolicita, "SolicitaCCustoId", "CCustoDesc");
            ViewBag.EmpCCustoId = new SelectList(db.EmpresaCC, "EmpCCustoId", "CCusto");
            ViewBag.UnidadeClasse = new SelectList(db.Unidade, "UnidadeId", "Nome");
            
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "RateioItemId")] RateioItem rateioItem)
        {
            var msg = "";
            var inserido = false;
            //return RedirectToAction("Index", "Relatorio",new {Id= rateioItem.RelatorioId });
            var cont= db.RateioItems.Where(d => d.RelatorioId == rateioItem.RelatorioId).Count();
            var desttotal = 0;
            if (cont > 0)
            {
                desttotal = db.RateioItems.Where(d => d.RelatorioId == rateioItem.RelatorioId).Select(d => d.Porcentagem).Sum();

            }
            if (desttotal+rateioItem.Porcentagem <= 100 & desttotal+ rateioItem.Porcentagem >= 0)
            {
                if (ModelState.IsValid)
                {
                    
                    
                    db.RateioItems.Add(rateioItem);
                    db.SaveChanges();
                    msg = "Concluido";
                    //return Json(new { Message = msg, Id = rateioItem.RelatorioId });
                    inserido = true;
                }
                else
                {
                    msg = "Ocorreu um erro verifique o formulario";
                }
            }
            else
            {
                msg = "Não foi possivel inserir, a porcentagem do item excede o limite do rateio";
            }
            return Json(new { Message = msg, Id = rateioItem.RelatorioId, inserido=inserido });
        }

        // GET: RateioItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RateioItem rateioItem = db.RateioItems.Find(id);
            if (rateioItem == null)
            {
                return HttpNotFound();
            }
            return View(rateioItem);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RateioItemId,SolicitanteCC,EmpCC,Classe,RelatorioId,SolicitaEmpresaId")] RateioItem rateioItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rateioItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rateioItem);
        }

        // GET: RateioItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RateioItem rateioItem = db.RateioItems.Find(id);
            if (rateioItem == null)
            {
                return HttpNotFound();
            }
            return View(rateioItem);
        }

        // POST: RateioItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RateioItem rateioItem = db.RateioItems.Find(id);
            db.RateioItems.Remove(rateioItem);
            db.SaveChanges();
            return RedirectToAction("Edit","Relatorio", new { id=rateioItem.RelatorioId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IntraNet.Mod.RDV/Views/RateioItems/Create.cshtml
@model IntraNet.Mod.RDV.Models.ViewModel.RateioItemViewModel

@{
    ViewBag.Title = "Create";
    Layout = null;
}

@using (Html.BeginForm("Create", "RateioItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4><i class="glyphicon glyphicon-plus">&nbsp;</i>Adicionar Item de Rateio</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <hr />
        <h5>Formulário para cadastro:</h5>
        <hr />
        <div class="alert alert-danger" id="AlertRateio">

        </div>
        <div class="row">

            <div class="form-group" style="padding-left: 5%">

                <div class="col-md-3">
                    @Html.Label("C.Custo:", htmlAttributes: new {@class = "control-label col-md-2"})
                    @Html.DropDownList("SolicitaCCustoId", null, "Selecione", new {@class = "form-control", @onchange = "CCustoSelector()"})    
                </div>

                <div class="col-md-2">
                    @Html.LabelFor(model => model.EmpCCustoId, "Codigo:", htmlAttributes: new {@class = "control-label col-md-2"})
                    @Html.DropDownListFor(model => model.EmpCCustoId, null, "000000", new {@class = "form-control", @disabled = "disabled", @placeholder = "0000000"})
                </div>

                <div class="col-md-2">
                    @Html.LabelFor(model => model.Item, htmlAttributes: new {@class = "control-label col-md-2"})
                    @Html.EditorFor(model => model.Item, new {htmlAttributes = new {@class = "form-control", @disabled = "disabled", @Value = ViewBag.Item}})

                </div>

                <div class="col-md-3">
                    @Html.LabelFor(model => model.UnidadeClasse, "Classe", htmlAttributes: new {@class = "control-label col-md-4"})
                    @Html.DropDownListFor(model => model.UnidadeClasse,null,"Selecione a Unidade",  htmlAttributes : new {@class = "form-control"})

                </div>

            </div>

            <div class="row" style="padding-left: 5%">

                <div class="col-md-3">
                    @Html.Label("Prospect:", htmlAttributes: new {@class = "control-label col-md-3"})
                    @Html.EditorFor(model => model.Prospect, new {htmlAttributes = new {@class = "form-control", @disabled = "disabled", @placeholder="Descreva o prospect"}})
     
                </div>

                <div class="col-md-2">
                    @Html.Label("Porcentagem:", htmlAttributes: new {@class = "control-label col-md-8"})
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Porcentagem, null, new { htmlAttributes = new { @class = "form-control", @placeholder = "000", type = "number", min = 0, max = 100 } })
                    </div>

                </div>

                <div class="col-md-5" align="right">
                    <br/>
                    <button type="button" value="Salvar" id="Salvar" class="btn btn-default" onclick="CriarRateioController()"> Salvar &nbsp;<i class="glyphicon glyphicon-ok"></i></button>
                    <button type="button" value="Salvar" id="btnSolicCCAddCancel" class="btn btn-default" onclick="btnCamcelarRateio()"> Cancelar &nbsp;<i class="glyphicon glyphicon-remove"></i></button>
                </div>
                <br/>
            </div>
            
        </div>
        
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntraNet.Mod.RDV/Views/RateioItems/Delete.cshtml
@model IntraNet.Domain.Entities.RateioItem

@{
    ViewBag.Title = "Delete";
    Layout = null;
}

<h2>Deletar</h2>

<h3>Tem certeza que deseja remover o Rateio para Centro de Custo: @Html.DisplayFor(model => model.empsCCusto.CCusto)?</h3>
<div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
        </div>
    }
</div>

IntraNet.Mod.RDV/Views/RateioItems/Details.cshtml
@model IntraNet.Domain.Entities.RateioItem

@{
    ViewBag.Title = "Details";
    Layout = null;
}

<h2>Details</h2>

<div>
    <h4>RateioItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.relatorio.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.relatorio.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.solicitaempresa.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.solicitaempresa.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SolicitanteCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SolicitanteCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Classe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Classe)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RateioItemId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IntraNet.Mod.RDV/Views/RateioItems/Edit.cshtml
@model IntraNet.Domain.Entities.RateioItem

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RateioItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RateioItemId)

        <div class="form-group">
            @Html.LabelFor(model => model.SolicitanteCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SolicitanteCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SolicitanteCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Classe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Classe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Classe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RelatorioId, "RelatorioId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RelatorioId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RelatorioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SolicitaEmpresaId, "SolicitaEmpresaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SolicitaEmpresaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SolicitaEmpresaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntraNet.Mod.RDV/Views/RateioItems/Index.cshtml
@model IEnumerable<IntraNet.Domain.Entities.RateioItem>

@{
    ViewBag.Title = "Index";
    Layout = null;
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Centro de Custo")
        </th>
        <th>
            @Html.DisplayName("Codigo")
        </th>
        <th>
            @Html.DisplayName("Item")
        </th>
        <th>
            @Html.DisplayName("Classe")
        </th>
        
        <th>
            @Html.DisplayName("Prorcentagem")
        </th>
        <th>
            @Html.DisplayName("Prospect")
        </th>
        <th>

        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.empsCCusto.CCustoDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.empsCCusto.CCusto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Item)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.unidade.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Porcentagem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prospect)
        </td>
        <td>
            <button onclick="DeletarRateio(@item.RateioItemId)" class="btn btn-default">Remover&nbsp;<i class="glyphicon glyphicon-remove"></i></button>
        </td>
    </tr>
}

</table>