IntraNet.Mod.RDV/Controllers/AdministradorController.cs
using IntraNet.Data.Repositories;
using System.Web.Mvc;

namespace IntraNet.Mod.RDV.Controllers
{
    [AllowAnonymous]
    public class AdministradorController : Controller
    {
        private EmpresaRepository _rep = new EmpresaRepository();
        
        // GET: Administrador
        //[Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ControleEmp()
        {
            return View();
        }
    }
}

IntraNet.Mod.RDV/Controllers/EmpCCustoController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using IntraNet.Data.Context;
using IntraNet.Domain.Entities;
using System;
using IntraNet.Data.Repositories;
using SelectListItem = System.Web.WebPages.Html.SelectListItem;

namespace IntraNet.Mod.RDV.Controllers
{
    public class EmpCCustoController : Controller
    {
        private EmpCCustoRepository _rep = new EmpCCustoRepository();
        EmpresaRepository _repEmp = new EmpresaRepository();
        SetorEmpRepository _repEmpDp = new SetorEmpRepository();
        UnidadeRepository _repUnid = new UnidadeRepository();
        // GET: EmpCCusto 
        public ActionResult Index()
        {
            
            var empresaCC = _rep.GetAll();
            return View(empresaCC.ToList());
        }

        // GET: EmpCCusto/Details/5
        public ActionResult Details(int id)
        {
            EmpCCusto empCCusto = _rep.RecuperarPorID(id);
            if (empCCusto == null)
            {
                return HttpNotFound();
            }
            return View(empCCusto);
        }

        // GET: EmpCCusto/Create
        public ActionResult Create()
        {
            var emp = _repEmp.GetAll().OrderByDescending(p => p.EmpresaId).FirstOrDefault().EmpresaId;
            ViewBag.EmpresaId = new SelectList(_repEmp.GetAll().Where(n=>n.EmpresaId == emp), "EmpresaId", "RazaoSocial");

            return View();
        }
        public ActionResult CreateEmpCC()
        {
            //ContextRDV db = new ContextRDV();
            ViewBag.EmpresaId = new SelectList(_repEmp.GetAll(), "EmpresaId", "RazaoSocial");
            ViewBag.EmpresaDeptoId = new SelectList(_repEmpDp.GetAll(), "EmpresaDeptoId", "DepartamentoDesc");
            ViewBag.UnidadeClasse = new SelectList(_repUnid.GetAll(),"UnidadeId","Nome");
            
            return View();
        }

        
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult CreateModel([Bind(Include = "EmpCCustoId,CCusto, CCustoDesc, EmpresaId, Projeto,Prospect ,  Ativo, Classe, Item, UnidadeId")] EmpCCusto empresacc)
        {
            var msg = "";
            empresacc.Ativo = true;
            if (ModelState.IsValid)
            {
                if (_rep.GetAll().Where(i => i.CCusto == empresacc.CCusto).Count() == 0 && _rep.GetAll().Where(i => i.CCustoDesc == empresacc.CCustoDesc).Count() == 0)
                {
                    _rep.Inserir(empresacc);
                    msg = "Concluido, inserido com sucesso!";
                }
                else
                {
                    msg = "Esse centro de custo ja está cadastrado!";
                }
            }
            else
            {
                msg = "Verifique o formulário!";
            }
            return Json(new { Message = msg });
        }        

        //GRID
        public JsonResult GetEmpCC( string sidx, string sort, int page, int rows)
        {
            ContextRDV db = new ContextRDV();

            sort = (sort == null) ? "" : sort;
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;

            var EmpCCList = (from u in db.EmpresaCC
                from e in db.Empresa.Where(e=>e.EmpresaId==u.EmpresaId).DefaultIfEmpty()
                from und in db.Unidade.Where(und=>und.UnidadeId == u.UnidadeClasse).DefaultIfEmpty()
                select new
                {
                    u.EmpCCustoId,
                    u.EmpresaId,
                    e.RazaoSocial,
                    Classe = u.UnidadeClasse,
                    Item = u.Item ?? "N/A",
                    Nome = und.Nome ?? "N/A",
                    Projeto = u.Projeto ?? false,
                    Prospect = u.Prospect ?? false,
                    u.CCusto,
                    u.CCustoDesc,
                    u.Ativo
                });

            int totalRecords = EmpCCList.Count();

            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
            if (sort.ToUpper() == "DESC")
            {
                EmpCCList = EmpCCList.OrderByDescending(t => t.EmpresaId);
                EmpCCList = EmpCCList.Skip(pageIndex * pageSize).Take(pageSize);
            }

            else
            {
                EmpCCList = EmpCCList.OrderBy(t => t.EmpresaId);
                EmpCCList = EmpCCList.Skip(pageIndex * pageSize).Take(pageSize);
            }

            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = EmpCCList
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        // GET: EmpCCusto/Edit/5
        public string Edit(EmpCCusto Model)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {
                    _rep.Alterar(Model);
                    msg = "Saved Successfully";
                }
                else
                {
                    msg = "Validation data not successfully";
                }
            }
            catch (Exception ex)
            {
                msg = "Error occured:" + ex.Message;
            }
            return msg;
        }
        public string Delete(int ID)
        {
            EmpCCusto empcc = _rep.GetAll().Where(i => i.EmpCCustoId == ID).Single();
            _rep.Remover(empcc);
            return "Deleted successfully";
        }

        public ActionResult GetUnidadeSelect(int id)
        {
            ContextRDV db = new ContextRDV();
            var msg = "";
            var unidadeList = new SelectList(db.Unidade, "UnidadeId", "Nome");
            if (id > 0)
            {
                unidadeList = null;
                unidadeList = new SelectList(db.Unidade, "UnidadeId", "Nome");
                
            }
            else
            {
                msg = "Verifique o formulário!";
            }
            return Json(new { Message = msg, Unidades = unidadeList });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _rep.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IntraNet.Mod.RDV/Views/Administrador/ControleEmp.cshtml
@{
    ViewBag.Title = "ControleEmp";
}
@Html.Partial("_AdmMenuPartialView")

<div class="container body-content" style="padding-left: 15%">
    <h2><i class="glyphicon glyphicon-wrench">&nbsp;</i>Controle - Centro de Custo</h2>
    <hr />
    <h5>Faça o controle dos Centro de Custo por Empresa:</h5>
    <hr />
    <div class="row" align="right">
        <!--BOTÕES-->
        <button class="btn btn-default" id="btnAddCCusto" onclick="btnAddCCusto()"><i class="glyphicon glyphicon-plus"></i> Novo C.Custo</button>
    </div>
    <div id="divAdd" runat="server">
        @*Html.Action("CreateEmpCC", "EmpCCusto", new { ID = Model.EmpresaId })*@
        @Html.Action("CreateEmpCC", "EmpCCusto")
    </div>
    <div class="container" align="right">
        <table id="jqGridEmpresaCC"></table>
        <div id="jqControlsEmpresaCC"></div>
    </div>
</div>
<!--MEU MODALA-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div id="MeuModal">
                </div>

            </div>
            <hr />
            <div align="right">
                <input type="button" value="Proximo" class="btn btn-default btnCadEmpCC" onclick="Proximo()" id="Proximo" disabled />
                <input name="btnFinaliza" type="button" value="Finalizar" class="btn btn-default btnFinaliza" id="Finalizar" onclick="Finaliza()" disabled />
            </div>
        </div>

    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
    <script src="~/Scripts/AdminMaster.js"></script>
    <script src="~/Scripts/AdminGrid.js"></script>
    <script src="~/Scripts/AdminCCusto.js"></script>
}

IntraNet.Mod.RDV/Views/Administrador/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@Html.Partial("_AdmMenuPartialView")
<h2 align="center"><i class="glyphicon glyphicon-align-justify">&nbsp;</i>&nbsp;Controle - Empresa, Unidades e Setores</h2>
<div class="container body-content" align="right" style="padding-left: 15%">
    
    <hr />
    <!-- DEVE FILTRAR A REUNIAO QUE USUÁRIO PARTICIPA-->
    <table id="jqGridEmpresa"></table>
    <div id="jqControlsEmpresa"></div>
    <br/>
    <div class="row">
        <div class="col-lg-6" align="left">
            <div class="col-lg-3">@Html.Label("EmpresaId:")&nbsp;</div><div class="col-lg-2">@Html.Editor("AlterarEmp", new { htmlAttributes = new { @class = "form-control AlterarEmp", @disabled = "disabled" } })</div>
        </div>
        <div class="col-lg-6" align="right">
            <button class="btn btn-default btnEdtEmp" id="">Alterar&nbsp;<i class="glyphicon glyphicon-pencil"></i></button>&nbsp;<button class="btn btn-default btnContCC" id="">C.Custo - Controle&nbsp;<i class="glyphicon glyphicon-wrench"></i></button>&nbsp;<button class="btn btn-default btnCadEmp" id="">Cadastrar&nbsp;<i class="glyphicon glyphicon-plus"></i></button>

        </div>
    </div>
        <hr />
    <table id="jqGridUnidade"></table>
    <div id="jqControlsUnidade"></div>
    <br />
    <button class="btn btn-default btnCadUnid" id="">Cadastrar&nbsp;<i class="glyphicon glyphicon-plus"></i></button>
    <hr />
    <table id="jqGridSetor"></table>
    <div id="jqGridSetor"></div>
    <br />
    <button class="btn btn-default btnCadDepto" id="">Cadastrar&nbsp;<i class="glyphicon glyphicon-plus"></i></button>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div id="MeuModal">
                </div>                
            </div>
        </div>
    </div>
</div>

@section scripts{
@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>  
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
<script src="~/Scripts/i18n/grid.locale-en.js"></script>
<script src="~/Scripts/jquery.jqGrid.min.js"></script>
<script src="~/Scripts/AdminMaster.js"></script>
<script src="~/Scripts/AdminGrid.js"></script>
<script src="~/Scripts/Repositories/UserPadraoRepositorie.js"></script>
<script src="~/Scripts/Interface/UserPadraoInter.js"></script>
}  